steps:
# Cloud Function steps
- name: 'docker.io/library/python:3.9'
  entrypoint: /bin/sh
  # Run pip install and pytest in the same build step
  # (pip packages won't be preserved in future steps!)
  args: [-c, 'pip install -r requirements.txt']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [
    'gcloud', 'functions', 'deploy', 'call_func',
    '--source', '.',
    '--project', 'clever-hangar-351317',
    '--runtime', 'python39',
    '--region', 'us-east4',
    '--memory', '512MB',
    '--timeout', '540s',
    '--trigger-topic', 'ps-every-5-mins-function-helloworld'
  ]
# Cloud Run job steps
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/clever-hangar-351317/cloud_run_jobs_helloworld', './run/jobs/']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/clever-hangar-351317/cloud_run_jobs_helloworld']
# Create container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['beta', 'run', 'jobs', 'update', 'cloud-run-jobs-helloworld', '--image', 'gcr.io/clever-hangar-351317/cloud_run_jobs_helloworld', '--region', 'us-east4']
  # args: ['beta', 'run', 'jobs', 'create', 'cloud-run-jobs-helloworld', '--image', 'gcr.io/clever-hangar-351317/cloud_run_jobs_helloworld', '--region', 'us-east4']

# #  Continuous deployment steps
# # Build the container image
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/clever-hangar-351317/cloud-run-jobs-helloworld-1:$COMMIT_SHA', './run/jobs']
# # Push the container image to Container Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/clever-hangar-351317/cloud-run-jobs-helloworld-1:$COMMIT_SHA']
# # Deploy container image to Cloud Run
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args:
#   - 'beta'
#   - 'run'
#   - 'jobs'
#   - 'deploy'
#   - 'cloud-run-jobs-helloworld-1'
#   - '--image'
#   - 'gcr.io/clever-hangar-351317/cloud-run-jobs-helloworld-1:$COMMIT_SHA'
#   - '--region'
#   - 'us-east4'
# images:
# - 'gcr.io/clever-hangar-351317/cloud-run-jobs-helloworld-1:$COMMIT_SHA'
# timeout: 60s  

# close to working - only frequency/schedule arg isn't working
# # Create Cloud Scheduler job to execute Cloud Run job on schedule
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args: ['scheduler', 'jobs', 'create', 'http', 'every-5-mins-cloudrunjob', '--location', 'us-east-4', 'frequency', '* 17-19 * * *', '--uri', 'https://us-east-4-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/clever-hangar-351317/jobs/cloud-run-jobs-helloworld:run', '--http-method', 'POST', '--oauth-service-account-email', '467888596638-compute@developer.gserviceaccount.com' ]


# gcloud scheduler jobs create http every-5-mins-cloudrunjob \
#   --location us-east-4 \
#   --schedule="* 17-19 * * *" \
#   --uri="https://us-east-4-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/clever-hangar-351317/jobs/cloud-run-jobs-helloworld:run" \
#   --http-method POST \
#   --oauth-service-account-email 467888596638-compute@developer.gserviceaccount.com

# images:
# - gcr.io/clever-hangar-351317/cloud_run_jobs_helloworld
